name: Deploy to GitHub Pages

on:
  push:
    branches: [main]          # change if your default branch is different
  workflow_dispatch:          # allows manual runs

permissions:
  contents: read
  pages:    write
  id-token: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: withastro/action@v3   # installs deps, runs `astro build`, uploads `dist/`

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
